services:
    postgres:
        image: postgres:latest
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres_user
            POSTGRES_DB: poker-planning
            PGDATA: "/var/lib/postgresql/data/pgdata"
        ports:
            - "5432:5432"
volumes:
    postgres_volume: